# Generated by Django 3.1.4 on 2021-02-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210208_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Active',
            field=models.BooleanField(default=False),
        ),
    ]
