# Generated by Django 3.1.4 on 2021-02-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DOB',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
