# Generated by Django 3.1.4 on 2021-02-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210208_1932'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
