# Generated by Django 3.1.4 on 2021-01-20 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_category_is_extention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term', models.CharField(max_length=100)),
                ('Definition', models.TextField()),
                ('Tick', models.BooleanField()),
                ('Mark', models.IntegerField(blank=True)),
                ('Lever', models.IntegerField(blank=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('CategoryID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='index.category')),
            ],
        ),
    ]
