# Generated by Django 3.1.4 on 2021-01-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_vocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='Tick',
            field=models.BooleanField(default=False),
        ),
    ]
