# Generated by Django 3.1.4 on 2021-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210420_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='Email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
