# Generated by Django 3.1.4 on 2021-01-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210120_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='Lever',
        ),
    ]
