# Generated by Django 3.1.4 on 2021-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_vocabulary_lever'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='Lever',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
