# Generated by Django 3.1.4 on 2021-01-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_vocabulary_lever'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='Lever',
        ),
    ]
